version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    container_name: api-db
  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./api/etherpadkey/APIKEY.txt:/api/opt/etherpad-lite/APIKEY.txt
    container_name: api-etherpad
  angular-ui:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    container_name: front
    volumes:
      - ./front:/front

